### ISSUE TITLE
No Mr. Mime/Mine Jr yet.

### ISSUE THREAD

**Issue by LaceyDS** [chainreactionboom/pokemon-sleep-grader#1]
I just pulled a Mime Jr. this morning, and can't find that on the drop-down of Pokemon. I hope you're able to add it soon. Thanks!

**Comment by kurokomu** [comment]
You can wait for an update, but there is a simple solution.
This is a simple tool that will produce the same score if the Pokémon have the same Specialty (berries, ingredients, skill). Thus, if you want to rate Mr. Mime, you can choose the same Ingredients Pokémon (e.g. Bulbasaur).

**Comment by ARasberry** [comment]
Im actively writing and should be nearly finished with adding the mime family. Ill update here when completed.

**Comment by chainreactionboom** [comment]
Sorry I forgot to check for a while. Now it was updated. Thanks for the PR @ARasberry!
